### ISSUE TITLE
Lodash doesn't work in Browserify

### ISSUE THREAD

**Issue by SLaks** [lodash/lodash#223]
I installed lodash from npm (both 1.1.0 and 1.1.1 fail), and ran through Browserify v1.17.3, and I got an error about invoking an undefined function.

The problem comes from the following line (in `runInContext()`):

```
// Avoid issues with some ES3 environments that attempt to use values, named
// after built-in constructors like `Object`, for the creation of literals.
// ES5 clears this up by stating that literals must use built-in constructors.
// See http://es5.github.com/#x11.1.5.
context = context ? _.defaults(window.Object(), context, _.pick(window, contextProps)) : window;
```

`window` is the outer `this` as passed to `(function (window) { ... }(this))`.  
In Browserify, `this` is `module.exports` (Browserify wraps lodash's source in its own function), which doesn't have any globals.  
Therefore, lines like `context.Array()` fail.

**Comment by ptarjan** [comment]
I'm on 3.8.0 and am still seeing this issue. Am I doing something wrong or did it regress?

**Comment by jdalton** [comment]
Hi @ptarjan! It works for me. I the deets. A snippet and the commands you're using would help.

**Comment by ptarjan** [comment]
Some more digging shows that `global.Object` is not defined by `browserify` in my context.

**Comment by ptarjan** [comment]
(Some more context, I'm trying to push a browserified module to Parse.com's Cloud Code and during their push process I'm getting the error while lodash is trying to register itself).

**Comment by ptarjan** [comment]
If I remove all the `var Foo = context.Foo` things as well as just setting `nativeParseInt = parseInt` then it deploys.

**Comment by jdalton** [comment]
A snippet and the commands you're using would help.

**Comment by iggied** [comment]
Is this implemented yet?  I am facing the issue even on the latest version (3.10.1). The patch suggested by @SLaks (if (typeof context.Object !== 'function') context = this;) does the trick. 

Do you suggest going to the Browserify team to find a solution to this issue?

**Comment by jdalton** [comment]
Naw, I simply cannot reproduce the issue and no one has managed to create a simple repro.

**Comment by ptarjan** [comment]
@jdalton the repro is very simple:

```
$ cat a.js
var _ = require('lodash');
$ browserify a.js > a.browserify.js
$ v8 a.browserify.js
a.browserify.js:720: TypeError: Cannot read property 'prototype' of undefined
    var arrayProto = Array.prototype,
                          ^
TypeError: Cannot read property 'prototype' of undefined
    at runInContext (a.browserify.js:720:27)
    at Object.<anonymous> (a.browserify.js:12322:11)
    at Object.<anonymous> (a.browserify.js:12353:3)
    at Object.1 (a.browserify.js:12355:4)
    at s (a.browserify.js:1:254)
    at a.browserify.js:1:305
    at Object.2.lodash (a.browserify.js:12357:9)
    at s (a.browserify.js:1:254)
    at e (a.browserify.js:1:425)
    at a.browserify.js:1:443

**Comment by jdalton** [comment]
a.js:
```js
var _ = require('lodash');
```
then
```bash
browserify a.js > a.browserify.js
```
works.

**Comment by ptarjan** [comment]
@jdalton what does "works" mean? Are you running the output in `v8` (which doesn't expose the global variables the same way as nodeJS does)?

**Comment by ptarjan** [comment]
For reference, v8 runs lodash fine without the browserify transform:

```
$ v8 node_modules/lodash/index.js
```

**Comment by jdalton** [comment]
Ah missed the `v8` bit. Hey 4 months late is better than never.

**Comment by ptarjan** [comment]
Sorry, I found a workaround so it didn't matter to me. One others piled on I cared more.

**Comment by jdalton** [comment]
![](http://media.giphy.com/media/rE190jy8ZWtiM/giphy.gif)

**Comment by jdalton** [comment]
The issue is resolved in master.

**Comment by ptarjan** [comment]
well then
![](http://www.jamesparton.info/wp-content/uploads/2013/03/shipit-300x275.png)

**Comment by jdalton** [comment]
It'll go out with v4.0.

**Comment by LiorArbel** [comment]
I seem to be having a problem - I've installed the latest versions of both lodash and browserify, and when I call require('lodash') the browser tries to preform a GET on localhost/[object%20Object], fails, and then breaks my whole javascript in unexplainable ways. 

I've investigated a little and found out that I can require every single category successfully through require('lodash/{category}') except for require('lodash/Object') which does exactly what I stated above.

I have no idea how to solve this, as I'm pretty new to browserify.

**Comment by magestican** [comment]
I am still seeing this occur inside of loadash 3.10.1

`var arrayProto = Array.prototype,  TypeError: Cannot read property 'prototype' of undefined`

Source :
  ```
  var arrayProto = Array.prototype,
        objectProto = Object.prototype,
        stringProto = String.prototype;
```

Then I see there is a guard being created specifically for loadash in my "browsered" js file : 

```
// Avoid issues with some ES3 environments that attempt to use values, named
    // after built-in constructors like `Object`, for the creation of literals.
    // ES5 clears this up by stating that literals must use built-in constructors.
    // See https://es5.github.io/#x11.1.5 for more details.
    context = context ? _.defaults(root.Object(), context, _.pick(root, contextProps)) : root;
```
Can I remove this guard someone through configuration?

**Comment by jdalton** [comment]
@magestican For v3 not so much. The issue is resolved in v4.
