### ISSUE TITLE
Need to publish lodash modules?

### ISSUE THREAD

**Issue by TSiege** [lodash/lodash#4193]
I'm using `lodash.clonedeep` in a library, and I got a security warning from github about it. However, when I tried to upgrade it seems like `lodash.clonedeep 4.5.0` is still the latest. Does this need to be republished or is github wrong about the security warning. `npm audit` came up with 0 warnings, so I just wanted to double check before ignoring the issue.

**Comment by jdalton** [comment]
Hi @TSiege!

They'll likely need to be updated. I'll try to get to it within the week. Until then though you can migrate to the primary `lodash` package and cherry-pick `lodash/cloneDeep`.

**Comment by adamkrogh** [comment]
Hi @jdalton , any update on this? Looks like `lodash.clonedeep` is still on `4.5.0` and last published three years ago: https://www.npmjs.com/package/lodash.clonedeep

We're getting a dependency flagged for security issues that depends on some of these lodash modules. Specifically, `sanitize-html` uses `lodash.isstring`, `lodash.mergewith`, and `lodash.clonedeep` which all have the same security issue that was fixed in the primary `lodash` package.

Any chance we could get these modules updated soon? Thanks!

**Comment by gabegorelick** [comment]
Still an issue with lodash.merge. Hard to force all your transitive deps to use `lodash` instead :(

**Comment by armenzg** [comment]
Is there a non-closed issue for this?
